[[headers]]
	for = "/*.(css|js|svg|woff2)"
	[headers.values]
	Cache-Control = "public, max-age=31536000, immutable" # 12 months

[[headers]]
	for = "/*"
	[headers.values]
	Permissions-Policy = "interest-cohort=()"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200
